import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/landing/navBar.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <header className="relative z-50 bg-secondary">
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
